/**
 * @file battery_config.c
 * 
 * @author Sam Donnelly (samueldonnelly11@gmail.com)
 * 
 * @brief Battery configuration 
 * 
 * @version 0.1
 * @date 2024-09-11
 * 
 * @copyright Copyright (c) 2024
 * 
 */

//=======================================================================================
// Includes 

#include "battery_config.h" 

//=======================================================================================


//=======================================================================================
// Zeee - 11.1V (3 cell), 1500mAh, LiPo 

// Notes: 
// - STM32 ADC operates in the range of 0-V_ref volts where V_ref is between 2.4V and 
//   3.6V with 3.3V being a common reference. This means the max digital value generated 
//   by the ADC with represent 3.3V. 
// - The STM32 ADC can have different resolutions (6, 8, 10 or 12 bits). Higher 
//   resolutions are more accurate / granular but take more time to convert. 
// - The battery used in this system is a 3-cell 12V battery and the voltage can 
//   comfortably range from 11-12V depending on the state of charge. Currently there 
//   isn't enough information gathered on the battery voltage range to have a better 
//   estimate at this time. Given that the battery is ~12V and the STM32 ADC is ~3.3V, 
//   the battery voltage has to be divided to get it within the correct range for the 
//   STM32 to both handle and convert so a resistor voltage divider is integrated into 
//   the system electrical circuit. Since the battery voltage range is narrow and it 
//   has to be dropped to fit the STM32 ADC voltage, the digital value produced can have 
//   a narrow range as well which means a higher resolution conversion is needed to get 
//   a more accurate voltage reading. 
// - The ADC voltage max and min values below are the max and min digital conversion 
//   values for this system. These were determined using the voltage range of the 
//   battery and the system voltage divider resistor values to find the equivalent 
//   voltage range within 0-3.3V. That equivalent voltage range was then converted to 
//   a digital value which is the value that's listed below. 
// - The max and min ADC voltage values below are currently based on 8-bit ADC 
//   resolution. The range is quite narrow so to get a better estimation of battery 
//   voltage for the user, a higher resolution must be used. 
// - The battery voltage range used to get the below max and min ADC digital voltage 
//   is 11-11.8V. This can be adjusted with better knowledge of the battery range and 
//   the right voltage divider to support it but this range is a relatively safe one. 

// Digital voltages - 0-1023 range (10-bit) 
const uint16_t 
adc_volt_min = 958,    // Min voltage - 3.09V ADC - 11.0V battery 
adc_volt_max = 1023;   // Max voltage - 3.30V ADC - 11.8V battery 


// Battery SOC calculation 
uint8_t battery_soc_calc(uint16_t voltage)
{
    // The SOC is found by taking the percentage the "voltage" is between the max and 
    // min values. In other words, the battery discharge is assumed to be linear between 
    // max and min. This is not 100% accurate but more information is needed on the 
    // battery to be able to create a more accurate model. "voltage" is the digital 
    // number that's generated by the ADC. For example, an 8-bit resolution ADC 
    // conversion will have a max number of 255 and a min number of 0. 
    return (voltage - adc_volt_min) * SCALE_100 / (adc_volt_max - adc_volt_min); 
}

//=======================================================================================
