#================================================================================
# File: mtbdl_data_analysis.py 
# 
# Author: Sam Donnelly (samueldonnelly11@gmail.com)
# 
# Description: MTBDL data analysis script 
#
# Date: July 27, 2023 
#================================================================================

#================================================================================
# Notes 

# Notes: 
# - A 'file_locations.py' script must be created in the 'analysis' folder (not 
#   a sub-folder within) for each local copy of this repository. This script 
#   contains the file locations of data used and generated by the analysis. It 
#   is not tracked by git as directories will change between machines. For file 
#   location names, see the comments and code below. 

#================================================================================

#================================================================================
# Includes 

import file_locations 

#================================================================================


#================================================================================
# Global variables 
#================================================================================


#================================================================================
# Main 
#================================================================================


#================================================================================
# Functions 
#================================================================================
